import Head from "next/head";
import { Inter } from "@next/font/google";
import { FaNodeJs } from "react-icons/fa";
import { SiFlutter,SiUnity,SiCsharp,SiVisualstudiocode } from "react-icons/si";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";

import Image from "next/image";
import benn from "../public/gsdgd.jpg";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black px-10 md:px-20 lg:px-20">
        <section className="min-h-screen">
          <nav className=" py-10 mb-10 flex justify-between" id="name_cv header">
            <section id="name">
              <h1 className=" text-lg font-tfont">BERKIN RENCBEROGLU</h1>
            </section>
            <ul className="flex items-center font-tfont">
              <li className=" text-white">
                CV Indir
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10 font-tfont ">
            <Image
              src={benn}
              className=" relative mx-auto rounded-full w-40 h-40"
            />
            <h3 className="text-2xl pt-6 max-w-xl mx-auto md:text-2xl">
              FRONTEND DEV.
            </h3>
            <p className="text-md py-3 leading-8 text-emerald-600 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-slate-300">
              <a href="https://www.linkedin.com/in/berkin-ren%C3%A7bero%C4%9Flu-3ab446145/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/Berkinrencberoglu?tab=repositories">
                <AiFillGithub />
              </a>
            </div>
          </div>
          <section id="tecrübelerim" className="text-center font-tfont">
            <h3 className="pt-6 max-w-xl mx-auto md:text-2xl">
              ÖZGEÇMISIM VE TECRÜBELERIM
            </h3>
            <p className="text-md py-3 leading-8 text-emerald-600 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
          </section>
          <section>
              <ul className="flex justify-center gap-5 text-center">
                <li>
                  <FaNodeJs className=" text-2xl cursor-pointer" />
                </li>
                <li>
                  <SiFlutter className=" text-2xl cursor-pointer" />
                </li>
                <li>
                  <SiCsharp className=" text-2xl cursor-pointer" />
                </li>
                <li>
                  <SiVisualstudiocode className=" text-2xl cursor-pointer" />
                </li>
                <li>
                  <SiUnity className=" text-2xl cursor-pointer "/>
                </li>
              </ul>
            </section>
            <section id="Projeler" className="text-center font-tfont">
            <h3 className="pt-6 max-w-xl mx-auto md:text-2xl">
              PROJELER
            </h3>

            </section>
        </section>
      </main>
    </>
  );
}
